server:
  port: 8080

spring:
  application:
    name: trading-backtester
  
  # H2 Database for Spring Batch metadata
  datasource:
    url: jdbc:h2:mem:backtestdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  # JPA/Hibernate settings
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    
  # H2 Console (for debugging)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Batch configuration
  batch:
    job:
      enabled: false  # Disable auto-run, we'll trigger manually
    jdbc:
      initialize-schema: always

# Google Cloud BigQuery Configuration
# Set bigquery.enabled=true to enable BigQuery integration
bigquery:
  enabled: ${BIGQUERY_ENABLED:false}

google:
  cloud:
    bigquery:
      project-id: ${GCP_PROJECT_ID:trading-backtester-dev}
      dataset-id: ${BIGQUERY_DATASET:trading_data}
      credentials-path: ${GOOGLE_APPLICATION_CREDENTIALS:}
      
# Alpha Vantage API (for market data)
alpha-vantage:
  api-key: ${ALPHA_VANTAGE_API_KEY:O1HMQYK5L1U9RVEW}
  base-url: https://www.alphavantage.co/query
  
# Application specific settings
trading:
  backtester:
    default-symbols: 
      - AAPL
      - TSLA
    batch-size: 1000
    chunk-size: 100
    
# Logging
logging:
  level:
    com.tradingbacktester: INFO
    org.springframework.batch: INFO
    com.google.cloud: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"