package com.tradingbacktester.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents a trading signal (BUY/SELL/HOLD) generated by a strategy
 */
public class TradingSignal {
    private String strategyId;
    private String symbol;
    private LocalDate signalDate;
    private SignalType signalType;
    private BigDecimal priceAtSignal;
    private BigDecimal signalStrength;  // 0.0 to 1.0, confidence in signal
    private LocalDateTime createdAt;
    private String metadata; // Additional strategy-specific info
    
    public enum SignalType {
        BUY, SELL, HOLD
    }
    
    // Default constructor
    public TradingSignal() {
        this.createdAt = LocalDateTime.now();
    }
    
    // Constructor for basic signal
    public TradingSignal(SignalType signalType, LocalDate signalDate, BigDecimal priceAtSignal) {
        this();
        this.signalType = signalType;
        this.signalDate = signalDate;
        this.priceAtSignal = priceAtSignal;
        this.signalStrength = BigDecimal.ONE; // Default full confidence
    }
    
    // Full constructor
    public TradingSignal(String strategyId, String symbol, LocalDate signalDate, 
                        SignalType signalType, BigDecimal priceAtSignal, BigDecimal signalStrength) {
        this();
        this.strategyId = strategyId;
        this.symbol = symbol;
        this.signalDate = signalDate;
        this.signalType = signalType;
        this.priceAtSignal = priceAtSignal;
        this.signalStrength = signalStrength;
    }
    
    // Getters and Setters
    public String getStrategyId() { return strategyId; }
    public void setStrategyId(String strategyId) { this.strategyId = strategyId; }
    
    public String getSymbol() { return symbol; }
    public void setSymbol(String symbol) { this.symbol = symbol; }
    
    public LocalDate getSignalDate() { return signalDate; }
    public void setSignalDate(LocalDate signalDate) { this.signalDate = signalDate; }
    
    public SignalType getSignalType() { return signalType; }
    public void setSignalType(SignalType signalType) { this.signalType = signalType; }
    
    public BigDecimal getPriceAtSignal() { return priceAtSignal; }
    public void setPriceAtSignal(BigDecimal priceAtSignal) { this.priceAtSignal = priceAtSignal; }
    
    public BigDecimal getSignalStrength() { return signalStrength; }
    public void setSignalStrength(BigDecimal signalStrength) { this.signalStrength = signalStrength; }
    
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    public String getMetadata() { return metadata; }
    public void setMetadata(String metadata) { this.metadata = metadata; }
    
    public boolean isBuySignal() {
        return SignalType.BUY.equals(signalType);
    }
    
    public boolean isSellSignal() {
        return SignalType.SELL.equals(signalType);
    }
    
    @Override
    public String toString() {
        return "TradingSignal{" +
                "symbol='" + symbol + '\'' +
                ", signalDate=" + signalDate +
                ", signalType=" + signalType +
                ", priceAtSignal=" + priceAtSignal +
                ", signalStrength=" + signalStrength +
                '}';
    }
}